### ISSUE TITLE
Betalingsløsning osv

### ISSUE THREAD

**Issue by jorgkv** [foss4g-nor/foss4g-nor-web#2]
Den statiske delen av siden var rask å oppdatere, men vi har ting som gjenstår:

Vi må finne en måte å håndtere påmeldinger og fakturere eller ta betalt fra de som melder seg på. Med nok sponsorer er det vel en mulighet for at vi kan få ned deltakeravgiften, men enn så lenge tror vi at vi trenger en betalingsløsning allikevel, også for å få registrert de som vil delta.

Alternativene sånn vi ser det er:
- Lage en betalingsløsning der man kan betale med kort, feks ved bruk av [stripe](https://stripe.com/)
- Lage en faktureringsløsning der man får tilsendt en epost med faktura etter å registrert navn og antall deltakere osv, feks ved bruk av [fakturo.no](http://www.fakturo.no/).
- At vi skriver under påmeldingen et kontonummer som man må overføre penger til for at påmeldingen skal være gyldig (enkelt å lage, men litt arbeid for både oss og de som skal betale).

Har dere fra norkart noen innspill på hva som kan fungere?

Sett bort i fra det siste alternativet trenger vi (hvis jeg tenker riktig) at siden kjører på en python eller node server for at vi skal kunne håndtere betalingsløsning og utsendelse av mail osv. Har fått beskjed om at vi skal lage noe og pushe det opp hit, men kan vi bruke node eller python eller noe da?

**Comment by alexanno** [comment]
Bra at dere er igang! Dere må gjerne hoste siden et annet sted hvor det ikke bare er statisk hosting - fks en digitalocean-boks eller tilsvarende. Jeg tipper "gullsponsorer" kan bidra med $5 i måneden til dette. 

Norkart eier foss4g.no-domenet, men det kan andre overta uten problemer - eller vi kan peke det mot andre steder. Men det er fint hvis dere bruker dette repoet, så kan andre overta all koden og alle kan se "historikken". 

Når det gjelder påmelding og fakturering så kan dette gjøres veldig enkelt med et enkelt skjema (i.e. google forms e.l.) med navn, epost, telefon, firma, fakturaadresse, fakturamerking. De aller fleste som deltar vil nok ønske en faktura tipper jeg. Det er jo litt arbeid med oppfølging i etterkant, men det er det jo verdt. 

Alternativt kan dere jo bruke paypal hvor selve betalingen også kan være påmeldingen.

**Comment by atlefren** [comment]
Mine 2cents er at det er mer pes å sette opp en fullverdig online betalingsløsning enn man vinner på det, men for all del, har dere tid og lyst er det bare å kjøre i gang! 

Github pages støtter bare statisk innhold, så da må dere som @alexanno sier hoste det et eller annet annet sted. Er også glad i DigitalOcean ;)

i 90% av tilfellene vil man nok ønske seg en faktura til arbeidsgiver istedenfor direktebetaling med kort,  men da er dere jo selv avhengige av fakturaer på det dere kjøper inn, dere har vel ikke noe stor kontantbeholdning.

Eller støtter jeg bifallet om at det er bra dere er i gang!

**Comment by jorgkv** [comment]
Vi dropper betalingsløsning og satser på faktura.

[faktoru.no](http://www.fakturo.no/api/resources/invoices) har et api som burde gjøre det greit nok å sette opp en node server som kan håndtere fakturagreiene når man sender inn et skjema via nettsiden.

Det er den eneste fakturatjenesten jeg så langt har sett som har et eget api.

Ellers har vi egentlig bestemt oss for datoen onsdag 23. september, og at vi satser på Felix i år og. Vi sjekket ut mange andre alternativer, også UIO og her på campus Ås. Felix endte opp som et av de beste alternativene uansett. 23. september blir uka etter den i Seoul. Vi håper noen av dere gira gutta skal dit i år og? Og at dere stiller opp med noe kjapt hipster-resyme a la ifjor!

**Comment by jorgkv** [comment]
Bare lurer, hva er forresten fordelen med DigitalOcean kontra feks Heroku og Google App Engine? En 5$ løsning vil være nok?
